/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import view.MainScreen;
public class App {

    public static void main(String[] args) {
        //Connection c = ConnectionFactory.getConnection();
        
        MainScreen mainScreen = new MainScreen();
        mainScreen.setVisible(true);
        //ConnectionFactory.closeConnection(c);
    }
}
